const sampleData = {
  products: [
    {
      name: 'Terra Couch',
      slug: 'terra-couch',
      description:
        'A striking blend of vintage charm and modern elegance, this orange leather sofa brings warmth and character to any space. Its rich, sun-kissed hue adds a bold statement, while the sleek lines and plush cushions ensure both comfort and style. The carefully crafted design, paired with high-quality materials, makes it a perfect centerpiece for living rooms, lounges, or creative spaces. Whether placed in a contemporary setting or a retro-inspired interior, this sofa invites relaxation with a timeless aesthetic.',
      images: ['/images/sample-products/terra-couch-francesca-tosolini.jpg'],
      authorImage: 'Francesca Tosolini',
      authorImageLink: '',
      price: 1299,
      brand: 'Veyla',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      categoryId: '00000000-0000-0000-0000-000000000000',
    },
    {
      name: 'Luna Sofa',
      slug: 'luna-sofa',
      description:
        "A perfect balance of comfort and functionality, the Luna Sofa embodies modern minimalism with a cozy touch. Its soft, neutral-toned fabric invites relaxation, while its clean lines seamlessly blend into any contemporary living space. Whether you're unwinding with a book, working from your laptop, or simply enjoying a quiet moment, this sofa enhances your home with effortless elegance and versatility.",
      images: ['/images/sample-products/luna-sofa-dennis-cortes.jpg'],
      authorImage: 'Dennis Cortes',
      authorImageLink: '',
      price: 1099,
      brand: 'Valen & Co.',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      categoryId: '00000000-0000-0000-0000-000000000000',
    },
    {
      name: 'Cloud Sofa',
      slug: 'cloud-sofa',
      description:
        'Soft, serene, and inviting, the Cloud Sofa is a sanctuary of comfort for any modern home. Its plush white cushions and minimalist design create a clean, fresh look, offering a calm and cozy atmosphere. Perfect for creating a relaxed and stylish environment, this sofa is the ideal choice for those who appreciate both simplicity and elegance in their living spaces.',
      images: ['/images/sample-products/cloud-sofa-blocks.jpg'],
      authorImage: 'Blocks',
      authorImageLink: '',
      price: 899,
      brand: 'Forma Casa',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      categoryId: '00000000-0000-0000-0000-000000000000',
    },
    {
      name: 'Mira Armchair',
      slug: 'mira-armchair',
      description:
        'The Mira Armchair combines refined craftsmanship with minimalist design. Featuring a sleek white padded seat and a striking black wooden frame, it offers both comfort and style. Its contemporary silhouette works seamlessly in both modern and traditional interiors, providing an elegant and inviting spot to relax or add a stylish accent to your space.',
      images: ['/images/sample-products/mira-armchair-eugenia-pankiv.jpg'],
      authorImage: 'Eugenia Pankiv',
      authorImageLink: '',
      price: 775,
      brand: 'Maison Solis',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      categoryId: '00000000-0000-0000-0000-000000000000',
    },
  ],
};

export default sampleData;
