import { hashSync } from 'bcrypt-ts-edge';

const sampleData = {
  users: [
    {
      name: 'Amelie',
      email: 'amliebarre@gmail.com',
      password: hashSync('Qwerty123*', 10),
      role: 'admin',
    },
    {
      name: 'John Doe',
      email: 'john.doe@example.com',
      password: hashSync('Qwerty123*', 10),
      role: 'admin',
    },
  ],
  categories: [
    {
      name: 'Armchairs',
      slug: 'armchairs',
      image: '/images/categories/armchair.jpg',
      authorImage: 'Afif Ramdhasuma',
      authorImageLink: 'https://unsplash.com/fr/@javaistan',
    },
    {
      name: 'Sofas',
      slug: 'sofas',
      image: '/images/categories/sofa.jpg',
      authorImage: 'Roberto Nickson',
      authorImageLink: 'https://unsplash.com/fr/@rpnickson',
    },
    {
      name: 'Chairs',
      slug: 'chairs',
      image: '/images/categories/chair.jpg',
      authorImage: 'Kari Shea',
      authorImageLink: 'https://unsplash.com/fr/@karishea',
    },
    {
      name: 'Coffee tables',
      slug: 'coffee-tables',
      image: '/images/categories/coffee-table.jpg',
      authorImage: 'Trend',
      authorImageLink: 'https://unsplash.com/fr/@trend_io',
    },
    {
      name: 'Side tables',
      slug: 'side-tables',
      image: '/images/categories/side-table.jpg',
      authorImage: 'Benjamin Voros',
      authorImageLink: 'https://unsplash.com/fr/@vorosbenisop',
    },
    {
      name: 'Accessories',
      slug: 'accessories',
      image: '/images/categories/accessories.jpg',
      authorImage: 'Simply Mersah',
      authorImageLink: 'https://unsplash.com/fr/@simplymersah',
    },
  ],
  products: [
    {
      name: 'Terra Couch',
      slug: 'terra-couch',
      description:
        'A striking blend of vintage charm and modern elegance, this orange leather sofa brings warmth and character to any space. Its rich, sun-kissed hue adds a bold statement, while the sleek lines and plush cushions ensure both comfort and style. The carefully crafted design, paired with high-quality materials, makes it a perfect centerpiece for living rooms, lounges, or creative spaces. Whether placed in a contemporary setting or a retro-inspired interior, this sofa invites relaxation with a timeless aesthetic.',
      image: '/images/sample-products/terra-couch.jpg',
      authorImage: 'Francesca Tosolini',
      authorImageLink: 'https://unsplash.com/fr/@fromitaly',
      price: 1299,
      brand: 'Veyla',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
    },
    {
      name: 'Luna Sofa',
      slug: 'luna-sofa',
      description:
        "A perfect balance of comfort and functionality, the Luna Sofa embodies modern minimalism with a cozy touch. Its soft, neutral-toned fabric invites relaxation, while its clean lines seamlessly blend into any contemporary living space. Whether you're unwinding with a book, working from your laptop, or simply enjoying a quiet moment, this sofa enhances your home with effortless elegance and versatility.",
      image: '/images/sample-products/luna-sofa.jpg',
      authorImage: 'Dennis Cortes',
      authorImageLink: 'https://unsplash.com/fr/@cortes',
      price: 1099,
      brand: 'Valen & Co.',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
    },
    {
      name: 'Cloud Sofa',
      slug: 'cloud-sofa',
      description:
        'Soft, serene, and inviting, the Cloud Sofa is a sanctuary of comfort for any modern home. Its plush white cushions and minimalist design create a clean, fresh look, offering a calm and cozy atmosphere. Perfect for creating a relaxed and stylish environment, this sofa is the ideal choice for those who appreciate both simplicity and elegance in their living spaces.',
      image: '/images/sample-products/cloud-sofa.jpg',
      authorImage: 'Blocks',
      authorImageLink: 'https://unsplash.com/fr/@blocks',
      price: 899,
      brand: 'Forma Casa',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
    },
    {
      name: 'Mira Armchair',
      slug: 'mira-armchair',
      description:
        'The Mira Armchair combines refined craftsmanship with minimalist design. Featuring a sleek white padded seat and a striking black wooden frame, it offers both comfort and style. Its contemporary silhouette works seamlessly in both modern and traditional interiors, providing an elegant and inviting spot to relax or add a stylish accent to your space.',
      image: '/images/sample-products/mira-armchair.jpg',
      authorImage: 'Eugenia Pankiv',
      authorImageLink: 'https://unsplash.com/fr/@eugenivy_now',
      price: 775,
      brand: 'Maison Solis',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
    },
    {
      name: 'Enigma',
      slug: 'enigma',
      description:
        "Apportez une touche de modernité à votre intérieur avec ce vase en céramique blanche au design épuré. Parfait pour mettre en valeur vos compositions florales, il s'intègre harmonieusement dans tout décor, qu'il soit contemporain ou classique. Fabriqué avec soin, ce vase allie simplicité et raffinement, faisant de lui un élément décoratif incontournable pour sublimer votre espace de vie.",
      image: '/images/sample-products/mira-armchair.jpg',
      authorImage: 'Linh Le',
      authorImageLink: 'https://unsplash.com/fr/@linhlee',
      price: 228,
      brand: "L'Atelier Blanc",
      rating: 4.5,
      numReviews: 10,
      stock: 10,
      isFeatured: false,
    },
  ],
};

export default sampleData;
